name: Selenium CI

on:
  push:
    branches:
      - main
      - feature/ci-fix
  pull_request:
    branches:
      - main
      - feature/ci-fix
  workflow_dispatch: # Permet de lancer le test manuellement via l'onglet Actions

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven' # Optionnel: accélère les prochains tests

      - name: Run tests
        run: mvn clean test